#!/bin/bash
# EMAIL SETUP CHECKLIST
# Follow these 3 steps to get emails working

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         📧 Email Setup Checklist (5 minutes)                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Step 1: Sign Up for Resend"
echo "   ├─ Go to: https://resend.com"
echo "   ├─ Click: Sign Up"
echo "   ├─ Verify: Your email"
echo "   └─ Time: 2 minutes"
echo ""
echo "✅ Step 2: Get Your API Key"
echo "   ├─ Log in to Resend"
echo "   ├─ Click: API Keys (left sidebar)"
echo "   ├─ Click: Create API Key"
echo "   ├─ Copy: The key (starts with re_)"
echo "   └─ Time: 1 minute"
echo ""
echo "✅ Step 3: Create .env.local File"
echo "   ├─ Create file: .env.local (in project root)"
echo "   ├─ Add this line:"
echo "   │  VITE_RESEND_API_KEY=re_your_key_here"
echo "   ├─ Replace: re_your_key_here with your actual key"
echo "   └─ Time: 1 minute"
echo ""
echo "✅ Step 4: Restart Dev Server"
echo "   ├─ If running: Press Ctrl+C"
echo "   ├─ Run: npm run dev"
echo "   └─ Time: 30 seconds"
echo ""
echo "✅ Step 5: Test It!"
echo "   ├─ Log in to the app"
echo "   ├─ Check in a bag"
echo "   ├─ Check your email inbox"
echo "   └─ Should arrive in ~5 seconds"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    That's it! 🎉                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📖 Need help? Read:"
echo "   • EMAIL_QUICK_START.md - Fast 3-step guide"
echo "   • RESEND_SETUP_GUIDE.md - Detailed with troubleshooting"
echo "   • EMAIL_SETUP_SIMPLE.md - Overview"
echo ""
